name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js for use with actions
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: '10.x'
      - run: npm install
      - run: yarn test
